### ISSUE TITLE
Discuss: Use namespace prefixes for Datastructure

### ISSUE THREAD

**Issue by ManasJayanth** [cedlemo/OCaml-GI-ctypes-bindings-generator#29]
The name clashing seems serious. We should let go of minimal names like List Buffer etc in favour of GList, GstBuffer etc.

**Comment by cedlemo** [comment]
I totally agree, we should formalize this. For now in GLib, I have the following names:

* GLib.DLList
* GLib.SLList
* GLib.Hash_table

As you see, I already changed the names using first letters of the type of datastructure for the list (ie: DLList: doubly-linked list, SLList: singly-linked list).

I am totally open to the idea of picking better names like `GList`, `GSList`.

**Comment by cedlemo** [comment]
done
